### ISSUE TITLE
misleading security language in the README

### ISSUE THREAD

**Issue by sknebel** [moyaproject/notes#1]
> so you can store secrets online without the requirement to trust your service provider.

is a claim you IMHO shouldn't make. The provider trivially could extend the javascript to upload the password or to sent the encrypted plaintext somewhere, unless you verify every single bit of code before each use.

**Comment by willmcgugan** [comment]
That is a good point.

**Comment by sknebel** [comment]
I think for self-hosting users it still is an interesting feature, because the contents of the notebooks can't be extracted from a backup or simply read by the server provider (if you use a VPS or similar), instead attacks require changes to the server or active MITM while a user is accessing the system. Maybe focus more on that aspect of things?

**Comment by willmcgugan** [comment]
It's definitely a self-hosting solution, for the reasons you mentioned. I don't see a way of completely removing the requirement to trust the server. If the database is compromised, the notes are safe enough. But if someone else has access to the server, they can inject anything they want in to the JS.

Open to suggestions for improvements...

**Comment by VoidWhisperer** [comment]
One (probably not well thought out idea) is to have something on the client side (an extension of some sort maybe?) that could check any scripts loaded against a set of scripts from a known-good copy of the website stored on the hard-drive, and if any of them differ or there is one that is there on the site that isn't on the HDD, alert the user? (As I said, not a very well thought-out idea, and not very effecient either.. also still leaves the issue of the MITM)

**Comment by willmcgugan** [comment]
Fine in theory, but it would make it hard to push minor updates. And if you need an extension you lose a lot of the benefit of it being a web application. I can't see a way of getting around needing to trust someone, at some point. I think SSL and self-hosting is probably as close as you'll get.

I'm not a security expert though. Could be wrong!

**Comment by naugtur** [comment]
Mega (https://mega.co.nz/) has their javastriot files verified clientside by a core js program transfered via an extra strong https (I don' remember the details).
They figured some stuff out and wrote about it. You could get inspired.

**Comment by willmcgugan** [comment]
Sounds like a great idea. Doubt I'll be inspired enough to go to the effort though. Maybe someone will implement something like that in a fork.

**Comment by chrstfer** [comment]
Could you use the client-side storage features as a script cache, along with a combination of pgp signing by the author and annotated (in doc-comment type comments? that might get unwieldy, but you wouldnt have to check comments for differences) diffs between the cached "known-good-copy" and the update. Or, on the same vein, in-browser application of annotated diff patches that have been signed by the author. 

I say annoted meaning that instead of just a changelog, the user has the option of reviewing every difference line-by-line with each group of changes being associated with some kind of explanation. Obviously not every user would go through with checking them, but the very ability to do so would take the trust away from both the server and the author in the same way open-source is already arguably safer than closed. 

Diff/patches are already well documented, and I'm sure there is a javascript implementation of sorts that you could extend to associate annotations with groups of changes; you could use PGP as it is. 

Just a thought, sorry for adding to a long-dead issue. I just know I do not have the time or will to fork and do this right now, so I wanted to get it out there.

**Comment by willmcgugan** [comment]
I think the problem is that there is a certain amount of trust required for the server. You could do something client side, but the server could then send you code that bypasses that. And even if you are a developer, you can't expect to have to analyse the scripts every time.

I think what you describe could only be done with some kind of plugin, or a desktop app. But if you have to install software, you lose much of the benefit of it being a web app. Maybe Mega have cracked that.
